### ISSUE TITLE
Cannot transition state via :crashed from :down

### ISSUE THREAD

**Issue by duhast** [kostya/eye#155]
Hi! During past weeks I often experience a full `eye` crash (along with monitored processes). The `eye history` output is empty, `eye i` shows only app/process names with no dots ending with status.

The log ends up with following:

```
07.11.2015 03:04:19 WARN  -- [leviathan:importer:thin-9000] check_alive: process <7757> not found
07.11.2015 03:04:19 WARN  -- [leviathan:importer:thin-9000] check_alive: process <7757> not found
07.11.2015 03:04:19 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
07.11.2015 03:04:19 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [287Mb, 287Mb, 287Mb, 288Mb, 0Mb] => OK
07.11.2015 03:04:20 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 2%] => OK
07.11.2015 03:04:20 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [287Mb, 287Mb, 288Mb, 0Mb, 0Mb] => OK
07.11.2015 03:04:20 INFO  -- [leviathan:importer:thin-9000] switch :crashed [:up => :down] (reason: crashed)
07.11.2015 03:04:20 ERROR -- [celluloid] Actor crashed!
StateMachine::InvalidTransition: Cannot transition state via :crashed from :down
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/state_machine-1.2.0/lib/state_machine/event.rb:252:in `block in add_actions'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `call'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/state_machine-1.2.0/lib/state_machine/machine.rb:765:in `block (2 levels) in define_helper'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/eye-0.7/lib/eye/process/states.rb:10:in `switch'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/eye-0.7/lib/eye/process/monitor.rb:43:in `check_alive'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/eye-0.7/lib/eye/process/watchers.rb:11:in `block in add_watchers'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/eye-0.7/lib/eye/process/watchers.rb:42:in `call'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/eye-0.7/lib/eye/process/watchers.rb:42:in `block in add_watcher'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:357:in `block in task'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:57:in `block in initialize'
    /opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:15:in `block in create'
07.11.2015 03:04:20 WARN  -- [celluloid] Terminating task: type=:timer, meta=nil, status=:callwait
    Celluloid::TaskFiber backtrace unavailable. Please try `Celluloid.task_class = Celluloid::TaskThread` if you need backtraces here.
07.11.2015 03:04:20 ERROR -- [leviathan:importer:thin-9000] trigger(flapping) task was terminated ["/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:34:in `terminate'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/eye-0.7/lib/eye/utils/leak_19.rb:7:in `block in to_proc'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `each'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:345:in `cleanup'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:329:in `shutdown'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:321:in `handle_crash'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:166:in `rescue in run'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:148:in `run'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor.rb:130:in `block in start'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/thread_handle.rb:13:in `block in initialize'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/actor_system.rb:32:in `block in get_thread'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `call'", "/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/internal_pool.rb:130:in `block in create'"]
```

What I'm doing wrong or how can I get over this issue? Is it an `eye` bug or my setup problem?
Thanks in advance.

**Comment by kostya** [comment]
Strange error. Looks like you somehow get 2 actors for 1 process (really strange).

This looks not normal: checks should be every second?
```
07.11.2015 03:04:19 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [287Mb, 287Mb, 287Mb, 288Mb, 0Mb] => OK
07.11.2015 03:04:20 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [287Mb, 287Mb, 288Mb, 0Mb, 0Mb] => OK
```

1) Show your config.
2) Show `eye x` output. Is "Eye::Process" count == processes count?
3) Was any exception before it in log?

**Comment by duhast** [comment]
> 1) Show your config

```ruby
require 'eye/notify/bugsnag'

APP_ENV = ENV.fetch('RACK_ENV')
APP_ROOT = "/var/www/leviathan_#{APP_ENV}/current"


BIND_PORT = ENV.fetch('LEVIATHAN_BIND_PORT').to_i
BIND_IP = ENV.fetch('LEVIATHAN_BIND_IP')

Eye.config do
  bugsnag api_key: ENV['BUGSNAG_LICENSE_KEY'], release_stage: APP_ENV, notify_release_stages: %w(staging production)
  contact :devs, :bugsnag, 'whatever'
end

Eye.application :leviathan do
  working_dir APP_ROOT
  notify :devs, :info
  stop_on_delete true

  env ENV.to_hash
  clear_bundler_env
  env 'BUNDLE_GEMFILE' => File.join(APP_ROOT, 'Gemfile')

  group :importer do
    trigger :flapping, times: 10, within: 1.minute, retry_in: 15.minutes, retry_times: 6
    check :cpu, below: 80, every: 30.seconds, times: 3
    check :memory, below: 485.megabytes, every: 30.seconds, times: [3, 5]

    chain action: :restart, grace: 5.seconds
    chain action: :start, grace: 0.2.seconds

    name = "thin-#{BIND_PORT}"
    pid_file_name = "tmp/pids/#{name}.pid"
    opts = [
      "--log log/#{name}.log",
      "--port #{BIND_PORT}",
      "--pid #{pid_file_name}",
      "--daemonize",
      "--rackup leviathan.ru",
      "--timeout 20",
      "--environment #{APP_ENV}",
      #"--chdir #{working_dir}",
      "--address #{BIND_IP}"
    ]

    process name do
      pid_file pid_file_name
      start_command "bundle exec thin start #{opts * ' '}"
      stop_signals [:QUIT, 2.seconds, :TERM, 1.seconds, :KILL]
      stdall "log/thin.stdall.log"
      restart_grace 8.seconds # just sleep this until process get up status (maybe enough to thin soft restart)
    end

  end
end
```

> 2) Show `eye x` output

```
about:     Eye v0.7 (c) 2012-2015 @kostya
resources: Oct23, 0%, 109Mb, <1242>
ruby:      ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
gems:      ["Celluloid=0.16.0", "Celluloid::IO=0.16.2", "StateMachine=1.2.0", "NIO=1.1.1", "Timers=4.0.4", "Sigar=1.7.0.0"]
logger:    /var/log/eye/eye.log
dir:       /home/deploy/.eye
pid_path:  /home/deploy/.eye/pid
sock_path: /home/deploy/.eye/sock
actors:    [["Celluloid::SupervisionGroup", 3], ["Eye::Utils::CelluloidChain", 2], ["Eye::Process", 1], ["Eye::Group", 1], ["Eye::Controller", 1], ["Eye::SystemResources::Cache", 1], ["Eye::Server", 1], ["Celluloid::IncidentReporter", 1], ["Celluloid::Notifications::Fanout", 1]]
```

I have only one process, so it seems the `Eye::Process` actor count is correct.
```
deploy@xxx-prod-yyy:/$ eye i
leviathan                  
  importer                         
    thin-9000 ..................... up  (08:25, 0%, 86Mb, <24434>)
```

> 3) Was any exception before it in log?

No, just the periodic checks.

**Comment by kostya** [comment]
1) то есть эта ошибка случилась в логе у этого eye который запущен 23 октября? и он все еще работает и мониторит этот процесс?
2) проверки memory также сейчас идут раз в секунду или нет?
3) легко ли это повторить если запустить eye с нуля?

**Comment by kostya** [comment]
также возможно связано с обновлением celluloid, они там таймеры перепилили сильно. можно попробовать eye 0.6.4

**Comment by duhast** [comment]
eye я сегодня перезапускал через upstart script - странно, что он думает, что он работает с 23 октября.

Проверки тикают не каждую секунду:
```
deploy@ххх-prod-ууу:/$ tail -f /var/log/eye/eye.log
11.11.2015 09:28:38 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
11.11.2015 09:28:38 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [90Mb, 90Mb, 90Mb, 90Mb, 90Mb] => OK
11.11.2015 09:29:08 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
11.11.2015 09:29:08 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [90Mb, 90Mb, 90Mb, 90Mb, 90Mb] => OK
11.11.2015 09:29:38 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
11.11.2015 09:29:38 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [90Mb, 90Mb, 90Mb, 90Mb, 90Mb] => OK
11.11.2015 09:30:08 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
11.11.2015 09:30:08 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [90Mb, 90Mb, 90Mb, 90Mb, 90Mb] => OK
11.11.2015 09:30:38 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
11.11.2015 09:30:38 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [90Mb, 90Mb, 90Mb, 90Mb, 90Mb] => OK
11.11.2015 09:31:08 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
11.11.2015 09:31:08 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [90Mb, 90Mb, 90Mb, 90Mb, 90Mb] => OK
11.11.2015 09:31:38 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
11.11.2015 09:31:38 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [90Mb, 90Mb, 90Mb, 90Mb, 90Mb] => OK
```

По идее, всё повторится через несколько дней, когда thin выжрет память и eye должен будет его перезапустить.

Попробую на одном хосте версию 0.6.4 - отпишусь.

**Comment by kostya** [comment]
ps aux | grep eye

вот щас кажись нормально, проблема начнется когда будут проверки одинаковые раз в секунду, откуда то берутся двойные таймеры, в них и проблема, может после деплоя?

**Comment by duhast** [comment]
Откатился до 0.6.4 - поглядим...

```
deploy@xxx-prod-yyy:/root$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
bugsnag (2.8.12)
bundler (1.10.6)
celluloid (0.15.2)
celluloid-io (0.15.0)
eye (0.6.4)
eye-bugsnag (0.0.1)
hitimes (1.2.3)
io-console (0.4.3)
json (1.8.1)
minitest (5.4.3)
nio4r (1.1.1)
power_assert (0.2.2)
psych (2.0.8)
rake (10.4.2)
rdoc (4.2.0)
sigar (0.7.3)
state_machine (1.2.0)
test-unit (3.0.8)
thor (0.19.1)
timers (4.0.4, 1.1.0)

deploy@xxx-prod-yyy:/root$ eye x
about:     Eye v0.6.4 (c) 2012-2015 @kostya
resources: 09:42, 0%, 22Mb, <29345>
ruby:      ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-linux]
gems:      ["Celluloid=0.15.2", "Celluloid::IO=0.15.0", "StateMachine=1.2.0", "NIO=1.1.1", "Timers=1.1.0", "Sigar=1.7.0.0"]
logger:    /var/log/eye/eye.log
dir:       /home/deploy/.eye
pid_path:  /home/deploy/.eye/pid
sock_path: /home/deploy/.eye/sock
actors:    [["Eye::Utils::CelluloidChain", 2], ["Celluloid::SupervisionGroup", 2], ["Eye::Process", 1], ["Eye::Group", 1], ["Eye::SystemResources::Cache", 1], ["Eye::Controller", 1], ["Eye::Server", 1], ["Celluloid::IncidentReporter", 1], ["Celluloid::Notifications::Fanout", 1]]
```

**Comment by duhast** [comment]
`ps` показываeт, что `eye` один

**Comment by kostya** [comment]
скорее всего будет норм, хотелось бы в 0.7 баг найти :)
посмотри по логу в какой момент начались проверки раз в секунду, там и будет баг скорее всего.

**Comment by duhast** [comment]
Посмотрю, спасибо за подсказку.

**Comment by kostya** [comment]
повторилась, может в старом логе посмотришь, где был баг?

**Comment by duhast** [comment]
В общем да, повторалось несколько раз на 0.7 и только один раз на 0.6.4. Причём только на хостах где [Grape](https://github.com/ruby-grape/grape) API (codename _leviathan_) на thin крутится. На хостах с главным Rails-приложением (там [Puma](http://puma.io/)) не случалось вообще. И только раз за много месяцев (недели полторы назад) было на отдельном хосте, где работает Sidekiq в 20 потоков.


Ситуация по логам везде одинаковая (смотрел несколько случаев):
```
20.11.2015 17:02:15 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:02:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [246Mb, 247Mb, 247Mb, 247Mb, 246Mb] => OK
20.11.2015 17:02:45 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:02:45 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 247Mb, 247Mb, 246Mb, 247Mb] => OK
20.11.2015 17:03:15 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:03:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 247Mb, 246Mb, 247Mb, 246Mb] => OK
20.11.2015 17:03:45 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:03:45 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 246Mb, 247Mb, 246Mb, 246Mb] => OK
20.11.2015 17:04:15 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:04:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [246Mb, 247Mb, 246Mb, 246Mb, 246Mb] => OK
20.11.2015 17:04:45 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:04:45 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 246Mb, 246Mb, 246Mb, 246Mb] => OK
20.11.2015 17:05:15 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:05:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [246Mb, 246Mb, 246Mb, 246Mb, 247Mb] => OK
20.11.2015 17:05:45 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:05:45 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [246Mb, 246Mb, 246Mb, 247Mb, 247Mb] => OK
20.11.2015 17:06:15 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:06:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [246Mb, 246Mb, 247Mb, 247Mb, 247Mb] => OK
20.11.2015 17:06:45 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:06:45 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [246Mb, 247Mb, 247Mb, 247Mb, 247Mb] => OK
20.11.2015 17:07:15 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:07:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 247Mb, 247Mb, 247Mb, 247Mb] => OK
20.11.2015 17:07:45 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:07:45 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 247Mb, 247Mb, 247Mb, 247Mb] => OK
20.11.2015 17:08:15 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:08:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 247Mb, 247Mb, 247Mb, 248Mb] => OK
20.11.2015 17:08:45 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:08:45 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 247Mb, 247Mb, 248Mb, 248Mb] => OK
20.11.2015 17:09:15 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 0%] => OK
20.11.2015 17:09:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 247Mb, 248Mb, 248Mb, 248Mb] => OK
20.11.2015 17:18:52 WARN  -- [leviathan:importer:thin-9000] check_alive: process <24356> not found
20.11.2015 17:18:52 WARN  -- [leviathan:importer:thin-9000] check_alive: process <24356> not found
20.11.2015 17:18:52 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 0%, 1%] => OK
20.11.2015 17:18:52 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 248Mb, 248Mb, 248Mb, 249Mb] => OK
20.11.2015 17:18:52 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [0%, 1%, 2%] => OK
20.11.2015 17:18:52 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [248Mb, 248Mb, 248Mb, 249Mb, 0Mb] => OK
20.11.2015 17:18:52 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [1%, 2%, 0%] => OK
20.11.2015 17:18:52 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [248Mb, 248Mb, 249Mb, 0Mb, 0Mb] => OK
20.11.2015 17:18:52 INFO  -- [leviathan:importer:thin-9000] check:cpu(<80%) [2%, 0%, 0%] => OK
20.11.2015 17:18:52 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [248Mb, 249Mb, 0Mb, 0Mb, 0Mb] => OK
20.11.2015 17:18:53 INFO  -- [leviathan:importer:thin-9000] switch :crashed [:up => :down] (reason: crashed)
20.11.2015 17:18:53 ERROR -- [celluloid] Actor crashed!
StateMachine::InvalidTransition: Cannot transition state via :crashed from :down
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/state_machine-1.2.0/lib/state_machine/event.rb:252:in `block in add_actions'
```

То есть проверки идут раз в 30 сек, затем после `check_alive: process <24356> not found` проверки в лог капают уже по несколько в секунду в течение пары секунд, потом exception.

Ещё заметил, что эксепшн не всегда один и тот-же. Возможные варианты:
* `ERROR -- [celluloid] Actor crashed!`
* `ERROR -- [celluloid] Eye::Process crashed!`

Но за ними всегда `StateMachine::InvalidTransition: Cannot transition state via :crashed from :down`.

На хосте с Sidekiq кино немного другое - всё нормально, потом Sidekiq берёт больше памяти, чем eye разрешил, eye его перезапускает, и валятся эксепшны.

Лог (стэктрэйсы обрезаны):
```
13.11.2015 13:47:06 INFO  -- [mps:sidekiq] check:cpu(<100%) [0%, 0%, 0%, 0%, 0%] => OK
13.11.2015 13:47:06 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1366Mb, 1366Mb, 1366Mb, 1366Mb, 1366Mb] => OK
13.11.2015 13:47:36 INFO  -- [mps:sidekiq] check:cpu(<100%) [0%, 0%, 0%, 0%, 0%] => OK
13.11.2015 13:47:36 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1366Mb, 1366Mb, 1366Mb, 1366Mb, 1366Mb] => OK
13.11.2015 13:48:06 INFO  -- [mps:sidekiq] check:cpu(<100%) [0%, 0%, 0%, 0%, 0%] => OK
13.11.2015 13:48:06 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1366Mb, 1366Mb, 1366Mb, 1366Mb, 1366Mb] => OK
13.11.2015 13:48:36 INFO  -- [mps:sidekiq] check:cpu(<100%) [0%, 0%, 0%, 0%, 1%] => OK
13.11.2015 13:48:36 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1366Mb, 1366Mb, 1366Mb, 1366Mb, 1366Mb] => OK
13.11.2015 13:49:06 INFO  -- [mps:sidekiq] check:cpu(<100%) [0%, 0%, 0%, 1%, 6%] => OK
13.11.2015 13:49:06 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1366Mb, 1366Mb, 1366Mb, 1366Mb, 1393Mb] => OK
13.11.2015 13:49:36 INFO  -- [mps:sidekiq] check:cpu(<100%) [0%, 0%, 1%, 6%, 9%] => OK
13.11.2015 13:49:36 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1366Mb, 1366Mb, 1366Mb, 1393Mb, 1411Mb] => OK
13.11.2015 13:50:06 INFO  -- [mps:sidekiq] check:cpu(<100%) [0%, 1%, 6%, 9%, 10%] => OK
13.11.2015 13:50:06 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1366Mb, 1366Mb, 1393Mb, 1411Mb, *1600Mb] => OK
13.11.2015 13:50:45 INFO  -- [mps:sidekiq] check:cpu(<100%) [1%, 6%, 9%, 10%, 11%] => OK
13.11.2015 13:50:47 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1366Mb, 1393Mb, 1411Mb, *1600Mb, *1668Mb] => OK
13.11.2015 13:51:21 INFO  -- [mps:sidekiq] check:cpu(<100%) [6%, 9%, 10%, 11%, 5%] => OK
13.11.2015 13:51:22 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1393Mb, 1411Mb, *1600Mb, *1668Mb, *1668Mb] => OK
13.11.2015 13:51:49 INFO  -- [mps:sidekiq] check:cpu(<100%) [9%, 10%, 11%, 5%, 5%] => OK
13.11.2015 13:51:53 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [1411Mb, *1600Mb, *1668Mb, *1668Mb, *1669Mb] => OK
13.11.2015 13:52:20 INFO  -- [mps:sidekiq] check:cpu(<100%) [10%, 11%, 5%, 5%, 5%] => OK
13.11.2015 13:52:20 INFO  -- [mps:sidekiq] check:memory(<1500Mb) [*1600Mb, *1668Mb, *1668Mb, *1669Mb, *1669Mb] => Fail
13.11.2015 13:52:20 ERROR -- [mps:sidekiq] NOTIFY: Bounded memory(<1500Mb): [*1600Mb, *1668Mb, *1668Mb, *1669Mb, *1669Mb] send to [:restart]
13.11.2015 13:53:11 INFO  -- [mps:sidekiq] schedule :restart (reason: bounded memory(<1500Mb))
13.11.2015 13:53:31 ERROR -- [celluloid] Actor crashed!
Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Cannot allocate memory)
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:29:in `rescue in deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
...
13.11.2015 13:53:33 ERROR -- [celluloid] Actor crashed!
Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Cannot allocate memory)
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:29:in `rescue in deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
...
13.11.2015 13:53:33 ERROR -- [celluloid] ERROR HANDLER CRASHED!
Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Cannot allocate memory)
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:29:in `rescue in deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
...
13.11.2015 13:53:33 ERROR -- [celluloid] Actor crashed!
Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Cannot allocate memory)
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:29:in `rescue in deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
...
13.11.2015 13:53:33 ERROR -- [celluloid] ERROR HANDLER CRASHED!
Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber: Cannot allocate memory)
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:29:in `rescue in deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks/task_fiber.rb:25:in `deliver'
	/opt/ruby-2.2.1/lib/ruby/gems/2.2.0/gems/celluloid-0.16.0/lib/celluloid/tasks.rb:96:in `resume'
...
```

Any suggestions?

P.S. У сайдкика RAM 2гб, у левиафана - 512Мб. Может проблема быть в объёме памяти (просто никакой лог об этом не сказал)?

**Comment by kostya** [comment]
насчет `Celluloid::DeadTaskError: cannot resume a dead task (can't alloc machine stack to fiber` это даже хз что это и как это повторить (чтото с памятью у celluloid или у руби) https://github.com/kostya/eye/issues/129

по твоему логу странен переход:
```
20.11.2015 17:09:15 INFO  -- [leviathan:importer:thin-9000] check:memory(<485Mb) [247Mb, 247Mb, 248Mb, 248Mb, 248Mb] => OK
20.11.2015 17:18:52 WARN  -- [leviathan:importer:thin-9000] check_alive: process <24356> not found
20.11.2015 17:18:52 WARN  -- [leviathan:importer:thin-9000] check_alive: process <24356> not found
```

между 17:09 и 17:18 - все стояло чтоли? и дальше сразу же появилось две одинаковые проверки (уже баг)

подозреваю может быть в этот момент в 17:09 был сделан `eye load` который сменил `Eye.config {logger ... }` поэтому тут записей нет, но есть где то в другом месте.

**Comment by kostya** [comment]
Возможно все дело в сильном лимите по памяти, вдруг там у сина резко скакнула память вышел в свап, eye каким то образом глюканул.

Там где puma там тоже сильно лимитирован сервак по памяти?

**Comment by duhast** [comment]
> между 17:09 и 17:18 - все стояло чтоли?
Затрудняюсь сказать - healthcheck начинает истерить только когда все три хоста упали.

> в этот момент в 17:09 был сделан eye load
Сам по себе - врядли. Деплоев небыло уже пару месяцев, а руками я перезапускаю eye (через upstart-script) только когда healthcheck заистерил.

> Возможно все дело в сильном лимите по памяти
Хз, но лимиты такие:
* sidekiq: 1500.megabytes of 2Gb
* rails/puma: 1400.megabytes of 2Gb
* grape/thin: 485.megabytes of 512Mb

**Comment by kostya** [comment]
`rails/puma: 1400.megabytes of 2Gb`
2gb это максимальная память на серваке?

в 17:09 - не уходил ли сервак в свап? можно посмотреть например по atop history

пока все выглядит крайне странно, никогда не встречал такой ошибки

можешь попробовать и 0.8, и руби 1.9.3? - на том серваке где чаще всего.

**Comment by duhast** [comment]
В общем, поколупался я ещё немного, но понять wtf так и не понял. Пробовать другие руби времени нет пока что, да и экспериментировать на продакшне не охота.
Пока что перешёл на upstart+[inspeqtor](https://github.com/mperham/inspeqtor)...

**Comment by paulccarey** [comment]
I also experience this problem?

Is it an open issue?

**Comment by kostya** [comment]
can you reproduce it? have your server cpu high usage, or memory in swap?
