### ISSUE TITLE
Raspberry Pi 2: client.rb:24:in `read': Connection reset by peer (Errno::ECONNRESET)

### ISSUE THREAD

**Issue by hackeron** [kostya/eye#158]
I get this trying to start eye on a Raspberry Pi 2 running Ubuntu:

```
$ bundle exec eye l recorder.eye 
/home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/client.rb:24:in `read': Connection reset by peer (Errno::ECONNRESET)
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/client.rb:24:in `block in send_request'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/client.rb:22:in `open'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/client.rb:22:in `send_request'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/client.rb:16:in `block in attempt_command'
	from /usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
	from /usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/client.rb:16:in `attempt_command'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/client.rb:12:in `command'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/cli/commands.rb:9:in `_cmd'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/cli/server.rb:7:in `server_started?'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/cli/server.rb:88:in `block in wait_server'
	from /usr/lib/ruby/2.1.0/timeout.rb:91:in `block in timeout'
	from /usr/lib/ruby/2.1.0/timeout.rb:35:in `block in catch'
	from /usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /usr/lib/ruby/2.1.0/timeout.rb:35:in `catch'
	from /usr/lib/ruby/2.1.0/timeout.rb:106:in `timeout'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/cli/server.rb:87:in `wait_server'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/cli/server.rb:61:in `server_start'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/lib/eye/cli.rb:98:in `load'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /home/deployer/.bundler/ruby/2.1.0/eye-410340bb7642/bin/eye:5:in `<top (required)>'
	from /var/lib/gems/2.1.0/bin/eye:23:in `load'
	from /var/lib/gems/2.1.0/bin/eye:23:in `<main>'
```

Any ideas?

**Comment by kostya** [comment]
looks like server crashed somehow, try foreground load `bundle exec eye l recorder.eye -f`

**Comment by hackeron** [comment]
This is what I see with foreground, hmmmm:

```
$ bundle exec eye l recorder.eye -f
I, [2015-11-18T00:56:55.524556 #24541]  INFO -- : Celluloid 0.17.2 is running in BACKPORTED mode. [ http://git.io/vJf3J ]
/usr/bin/ruby2.1: symbol lookup error: /var/lib/gems/2.1.0/extensions/arm-linux/2.1.0/sigar-0.7.3/sigar.so: undefined symbol: sigar_skip_token
```

**Comment by hackeron** [comment]
This seems to be the workaround: https://github.com/hyperic/sigar/issues/60

Closing as this is not an eye bug.
