### ISSUE TITLE
Sidekiq reported as crashed, spamming processes

### ISSUE THREAD

**Issue by milgner** [kostya/eye#165]
We have been using eye for a couple of months but twice in the last few weeks it started spamming Sidekiq instances when it somehow thought that the process had crashed.

From the logs:

```
24.02.2016 06:52:32 WARN  -- [app:sidekiq] compare_identity: fail, pid_file: '24 Feb 06:51', process: '24 Feb 06:52' (sidekiq 3.5.4 app [3 of 20 busy])
24.02.2016 06:52:32 INFO  -- [app:sidekiq] switch :crashed [:up => :down] (reason: crashed_by_identity)
24.02.2016 06:52:32 INFO  -- [app:sidekiq] check:cpu(<100%) [0%] => OK
24.02.2016 06:52:32 INFO  -- [app:sidekiq] check:memory(<400Mb) [182Mb, 202Mb] => OK
24.02.2016 06:52:32 INFO  -- [app:sidekiq] schedule :check_crash (reason: crashed)
24.02.2016 06:52:32 INFO  -- [app:sidekiq] delete pid_file: PIDFILE_PATH
24.02.2016 06:52:32 INFO  -- [app:sidekiq] => check_crash  (reason: crashed)
24.02.2016 06:52:32 WARN  -- [app:sidekiq] check crashed: process is down
24.02.2016 06:52:32 INFO  -- [app:sidekiq] schedule :restore (reason: crashed)
24.02.2016 06:52:32 INFO  -- [app:sidekiq] <= check_crash
24.02.2016 06:52:32 INFO  -- [app:sidekiq] => restore  (reason: crashed)
24.02.2016 06:52:32 INFO  -- [app:sidekiq] load_external_pid_file: pid_file not found
24.02.2016 06:52:32 INFO  -- [app:sidekiq] switch :starting [:down => :starting] (reason: crashed)
```

Our configuration is pretty standard and it usually(tm) just works, too :)

```
  process 'sidekiq' do
    start_command "bin/bundle exec sidekiq -e #{RAILS_ENV} -C #{APP_DIR}/config/sidekiq.yml"
    pid_file "#{APP_DIR}/tmp/pids/#{name}.pid"
    daemonize true
    stop_signals [:USR1, 0, :TERM, 10.seconds, :KILL]
    check :cpu, every: 60, below: 100, times: 5
    check :memory, every: 30, below: 400.megabytes, times: 5
  end
```

Another thing I noticed is that when I ran `eye stop sidekiq`, it suddenly forgot about all the other processes it was monitoring: running `eye info` afterwards only showed:

```
app                    
  sidekiq ......................... unmonitored (stop by user at 09 Mar 08:16)
```

Luckily, the other processes were still running, only it looks like Eye forgot about them.

**Comment by kostya** [comment]
thanks for report, 

eye think that it monitored wrong process. from 0.8 version eye periodically check the process identity, comparing pid_file timestamp, and the process start_time and if it different more than 60.seconds, mark processes as dead. In normal situation this should not happen, if it happen something wrong with process or config.

Is sidekiq using some kind of self-deamonization?
Is there any pid_file setting in `#{APP_DIR}/config/sidekiq.yml`?

as workaround you can set `check_identity false` on top of Application config, or process config. or `check_identity_grace 5.minutes`

also why this?: `delete pid_file: PIDFILE_PATH` is it correct?

about second question, this is strange, may be some exception in log?

**Comment by milgner** [comment]
Thank you for the feedback! Sidekiq indeed has a PID configured, it's the right one in the logs and as I mentioned it usually works just great. I will try using `check_identity_grace` and check that it does the trick.

I overlooked it before but when I searched the log for exceptions once more, I found this backtrace from when I was trying to triage the process:

```
09.03.2016 08:10:24 ERROR -- [celluloid] Actor crashed!
NoMethodError: undefined method `[]' for nil:NilClass
  $GEMPATH/eye-0.8/lib/eye/process/commands.rb:16:in `start_process'
  $GEMPATH/eye-0.8/lib/eye/process/controller.rb:12:in `start'
  $GEMPATH/eye-0.8/lib/eye/process/monitor.rb:115:in `restore'
  $GEMPATH/eye-0.8/lib/eye/process/scheduler.rb:49:in `scheduled_action'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
  (celluloid):0:in `remote procedure call'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/call/sync.rb:45:in `value'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:22:in `method_missing'
  $GEMPATH/eye-0.8/lib/eye/utils/celluloid_chain.rb:68:in `process'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'
  $GEMPATH/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'
```

**Comment by kostya** [comment]
hm, i not see any reason for this exception, because here `commands.rb:16` variables can't be nil (no way). so may be this is also celluloid bug (in switching contexts). can you try eye v `0.8.celluloid15`

**Comment by maksimf** [comment]
Looks like I've got similar issue:

```
10.03.2016 12:51:50 INFO  -- [Eye] <= command: load /*path*/current/config/eye.rb (0.163648842s)
10.03.2016 12:51:50 INFO  -- schedule :monitor (reason: monitor by user)
10.03.2016 12:51:50 INFO  -- => monitor  (reason: monitor by user)
10.03.2016 12:51:50 INFO  -- <= monitor
10.03.2016 12:51:50 INFO  -- process <31415> from pid_file is already running
10.03.2016 12:51:50 INFO  -- switch :already_running [:unmonitored => :up] (reason: monitor by user)
10.03.2016 12:51:50 INFO  -- <= monitor
10.03.2016 12:51:55 WARN  -- check_alive: process <31415> not found
10.03.2016 12:51:55 INFO  -- delete pid_file: /*path*/current/tmp/pids/sidekiq.pid
10.03.2016 12:51:55 INFO  -- switch :crashed [:up => :down] (reason: crashed)
10.03.2016 12:51:55 INFO  -- schedule :check_crash (reason: crashed)
10.03.2016 12:51:55 INFO  -- => check_crash  (reason: crashed)
10.03.2016 12:51:55 WARN  -- check crashed: process is down
10.03.2016 12:51:55 INFO  -- schedule :restore (reason: crashed)
10.03.2016 12:51:55 INFO  -- <= check_crash
10.03.2016 12:51:55 INFO  -- => restore  (reason: crashed)
10.03.2016 12:51:55 INFO  -- pid_file not found, starting...
10.03.2016 12:51:55 INFO  -- switch :starting [:down => :starting] (reason: crashed)
10.03.2016 12:51:55 INFO  -- daemonizing: `bundle exec sidekiq -e production -C /*path*/current/config/sidekiq.yml` with start_grace: 2.5s, env: 'RAILS_ENV=production RBENV_ROOT=~/.rbenv/ RBENV_VERSION=2.2.4 BUNDLE_GEMFILE=/*path*/current/Gemfile', <32231> (in /*path*/current)
10.03.2016 12:51:55 INFO  -- [skippr:background_jobs:sidekiq] sleeping for :start_grace 2.5
10.03.2016 12:51:58 INFO  -- [skippr:background_jobs:sidekiq] switch :started [:starting => :up] (reason: crashed)
10.03.2016 12:51:58 INFO  -- [skippr:background_jobs:sidekiq] <= restore
```

**Comment by kostya** [comment]
not a similar, you have no `compare_identity: fail` in log

**Comment by maksimf** [comment]
I'll gather more info

**Comment by milgner** [comment]
Things looked ok for some time after setting a higher `check_identity_grace` but today the problem occurred again. Looks like I have to set `check_identity false`.

**Comment by kostya** [comment]
is it ok with check_identity false?

**Comment by artshpakov** [comment]
I'm experiencing the same issue. Any luck working it out?

````
20.08.2016 23:16:02 WARN  -- [myapp:sidekiq] check_alive: process <3006> not found
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] delete pid_file: /Code/Ruby/myapp/tmp/pids/sidekiq.pid
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] switch :crashed [:up => :down] (reason: crashed)
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] schedule :check_crash (reason: crashed)
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] => check_crash  (reason: crashed)
20.08.2016 23:16:02 WARN  -- [myapp:sidekiq] check crashed: process is down
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] schedule :restore (reason: crashed)
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] <= check_crash
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] => restore  (reason: crashed)
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] load_external_pid_file: pid_file not found
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] switch :starting [:down => :starting] (reason: crashed)
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] daemonizing: `bundle exec sidekiq` with start_grace: 2.5s, env: 'RAILS_ENV=development', <3032> (in Code/Ruby/myapp)
20.08.2016 23:16:02 INFO  -- [myapp:sidekiq] sleeping for :start_grace 2.5
````

**Comment by kostya** [comment]
@artshpakov in your log i not see any problem, what you problem?

**Comment by artshpakov** [comment]
@kostya well, it goes into crash/restart loop and ends up flapping eventually.
Eye is v0.8.1, sidekiq is 4.1.2 (updating to 4.1.4 didn't help, so I rolled back to 4.1.2). Config is rather basic:
````
RAILS_ENV = ENV['RAILS_ENV'] || 'development'
ROOT = File.expand_path(File.join(File.dirname(__FILE__), '..'))

Eye.config do
  logger "#{ROOT}/log/eye.log"
end

Eye.application 'myapp' do
  env 'RAILS_ENV' => RAILS_ENV
  working_dir ROOT
  trigger :flapping, times: 5, within: 1.minute

  group :app do
    process :puma do
      daemonize true
      pid_file "tmp/pids/puma.pid"
      stdall "log/puma.log"

      start_command "bundle exec puma -C #{ROOT}/config/puma/#{RAILS_ENV}.rb config.ru"
      stop_signals [:TERM, 5.seconds, :KILL]
      restart_command 'kill -USR2 {PID}'

      check :cpu, every: 10, below: 80, times: 3
      check :memory, every: 10, below: 100.megabytes, times: [3, 5]
    end

    process :sidekiq do
      daemonize true
      pid_file "tmp/pids/sidekiq.pid"
      stdall "log/sidekiq.log"

      start_command "bundle exec sidekiq"
      stop_signals [:USR1, 30.seconds, :TERM]

      check :cpu, every: 30, below: 80, times: 5
      check :memory, every: 30, below: 100.megabytes, times: 5
    end
  end
end
````

**Comment by kostya** [comment]
just tested sidekiq, no any problem.
what in your `log/sidekiq.log`

**Comment by artshpakov** [comment]
@kostya thanks for your help, the problem was in misconfiguration in another part of the app. Sorry for the false alarm.

**Comment by k41n** [comment]
👍
