### ISSUE TITLE
eye fails to start: ~/.eye (Errno::EACCES)

### ISSUE THREAD

**Issue by jelmd** [kostya/eye#166]
The full stack trace is:

```
/local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /local/home/foo/.eye (Errno::EACCES)
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/local.rb:42:in `ensure_eye_dir'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli/server.rb:46:in `server_start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli.rb:99:in `load'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/bin/eye:5:in `<top (required)>'
    from /local/home/foo/bin/eye:16:in `load'
    from /local/home/foo/bin/eye:16:in `<main>'
socket(/local/home/foo/.eye/sock) not found, did you run `eye load`?
All workers killed.
/local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /local/home/foo/.eye (Errno::EACCES)
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/local.rb:42:in `ensure_eye_dir'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli/server.rb:46:in `server_start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli.rb:99:in `load'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/bin/eye:5:in `<top (required)>'
    from /local/home/foo/bin/eye:16:in `load'
    from /local/home/foo/bin/eye:16:in `<main>'
/local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /local/home/foo/.eye (Errno::EACCES)
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/local.rb:42:in `ensure_eye_dir'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli/server.rb:46:in `server_start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli.rb:99:in `load'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/bin/eye:5:in `<top (required)>'
    from /local/home/foo/bin/eye:16:in `load'
    from /local/home/foo/bin/eye:16:in `<main>'
/local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /local/home/foo/.eye (Errno::EACCES)
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/local.rb:42:in `ensure_eye_dir'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli/server.rb:46:in `server_start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli.rb:99:in `load'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/bin/eye:5:in `<top (required)>'
    from /local/home/foo/bin/eye:16:in `load'
    from /local/home/foo/bin/eye:16:in `<main>'
/local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `mkdir': Permission denied @ dir_s_mkdir - /local/home/foo/.eye (Errno::EACCES)
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:250:in `fu_mkdir'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:224:in `block (2 levels) in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `reverse_each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:222:in `block in mkdir_p'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `each'
    from /local/usr/ruby/versions/2.1.8/lib/ruby/2.1.0/fileutils.rb:208:in `mkdir_p'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/local.rb:42:in `ensure_eye_dir'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli/server.rb:46:in `server_start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/lib/eye/cli.rb:99:in `load'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /local/home/foo/ruby/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /local/home/foo/ruby/2.1.0/gems/eye-0.8/bin/eye:5:in `<top (required)>'
    from /local/home/foo/bin/eye:16:in `load'
    from /local/home/foo/bin/eye:16:in `<main>'
```

**Comment by kostya** [comment]
when you run eye under user, it try to create folder `~/.eye`, so in your case, it can't create this folder, maybe have no permissions?

**Comment by jelmd** [comment]
Of course it does not have permission to write into the app-owner's directory. Our policy is, that inet exposed service run under a non-privileged user, usually with home == /. So seems to be a design flaw or is there a config param, which can be used ?

**Comment by kostya** [comment]
you can use `leye`, to run eye in project folder https://github.com/kostya/eye/wiki/What-is-loader_eye-and-leye

or you can set EYE_HOME env variable: `EYE_HOME=/some/dir eye l some_config.eye`

**Comment by jelmd** [comment]
Ahh ok, setting EYE_HOME seems to work wrt. start (i.e. `EYE_HOME=/local/home/foo/tmp ${RUBY}/bin/eye load app.eye "$@"` as un-privileged user). However, for stop it doesn't, if executed by root:
```
# ${RUBY}/bin/eye quit --eyehome=/local/home/foo/tmp --stop-all
ERROR: "eye quit" was called with arguments ["--eyehome=/local/home/foo/tmp"]
Usage: "eye quit"

# ${RUBY}/bin/leye quit --eyehome=/local/home/foo/tmp --stop-all
ERROR: "leye quit" was called with arguments ["--eyehome=/local/home/foo/tmp"]
Usage: "leye quit"

# EYE_HOME=/local/home/foo/tmp ${RUBY}/bin/eye quit --stop-all
socket(/var/run/eye/sock) not found, did you run `eye load`?

# EYE_HOME=/local/home/foo/tmp ${RUBY}/bin/leye quit --stop-all
socket(/var/run/eye/sock) not found, did you run `eye load`?
```

**Comment by kostya** [comment]
yes when you call eye from root, it ignore EYE_HOME, and using /var/run/eye/ which seems not really cool at all, i think need to fix it.

**Comment by jelmd** [comment]
Yes, thanx :)

Wrt. examples: Sorry, there is no sudo installed. However 'bundle exec eye' is just the longer version of ${RUBY}/bin/eye (i.e. the result of `bundler install --binstubs ${RUBY}/bin`) and `# sudo -u foo -H ...` is similar to `# su - foo -c "..."`, so both should work, yes.

**Comment by kostya** [comment]
fixed in https://github.com/kostya/eye/issues/206?
