### ISSUE TITLE
HTTP.post timing out/intermittent inside eye? (starting_guard)

### ISSUE THREAD

**Issue by xanview** [kostya/eye#189]
The HTTP library I'm using here is this: https://github.com/httprb/http

I have 2 processes running, one is this. It is sending a request in a loop to make sure the rails process is working correctly (just for the purposes of this test):

```ruby
$ bundle exec rails c production
> loop { TIME { puts HTTP.post('http://127.0.0.1:3001/api/v2/cameras/update', json: {:token=>"test", :id=>"test", :camera=>{:analytics_state=>:ok}}) }; sleep 0.1 }
{"status":"ok"}
  0.000000   0.010000   0.010000 (  0.028937)
{"status":"ok"}
  0.010000   0.000000   0.010000 (  0.011525)
{"status":"ok"}
  0.000000   0.000000   0.000000 (  0.011964)
{"status":"ok"}
...
```

In my eye file, here are the relevant parts:

```ruby
def camera_working?(url)
  url = 'http://127.0.0.1:3001/api/v2/cameras/update'
  params =  {:token=>"test", :id=>"test", :camera=>{:analytics_state=>:ok}}
  begin
    puts HTTP.post(url, json: params)
  rescue => exception
    logger.error "Could not update camera stream state value #{url} #{params}"
    logger.error exception.backtrace
  end
  true
end

process :proxy do
    ...
    trigger :starting_guard, every: 30.seconds, should: -> {
      camera_working?(url) }
   ...
```

In the above logic, the camera_working? is always returning true and eye works correctly and starts the process regardless of the result. However, I am seeing this in the logs which I shouldn't be:

```
$ bundle exec eye restart
$ tail eye.log
...
[2017-02-15 23:33:16 +0000] [recorder:58a44a093d1f920c1ed58aee:proxy2] trigger(starting_guard) Could not update camera stream state value http://127.0.0.1:3001/api/v2/cameras/update {:token=>"test", :id=>"test", :camera=>{:recording_state=>:ok}}
[2017-02-15 23:33:16 +0000] [recorder:58a44a093d1f920c1ed58aee:proxy2] trigger(starting_guard) ["/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/timeout/global.rb:107:in `wait_readable'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/timeout/global.rb:107:in `wait_readable_or_timeout'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/timeout/global.rb:90:in `block in perform_io'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/timeout/global.rb:85:in `loop'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/timeout/global.rb:85:in `perform_io'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/timeout/global.rb:51:in `readpartial'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/connection.rb:212:in `read_more'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/connection.rb:99:in `block in read_headers!'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/connection.rb:98:in `loop'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/connection.rb:98:in `read_headers!'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/client.rb:64:in `perform'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/client.rb:41:in `request'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/http-2.2.1/lib/http/chainable.rb:26:in `post'", "/data/deployer/timeagent/eye/rtsp_checker.rb:21:in `update_camera_stream_status'", "/data/deployer/timeagent/eye/rtsp_checker.rb:64:in `camera_rtsp_stream_working?'", "/data/deployer/timeagent/eye/rtsp_checker.rb:96:in `camera_stream_working?'", "/data/deployer/timeagent/eye/rtsp_checker.rb:120:in `camera_working?'", "/data/deployer/timeagent/eye/helpers.rb:148:in `block (2 levels) in proxy_rtsp'", "/data/deployer/timeagent/vendor/cache/eye-51cdc5f92297/lib/eye/trigger.rb:103:in `instance_exec'", "/data/deployer/timeagent/vendor/cache/eye-51cdc5f92297/lib/eye/trigger.rb:103:in `exec_proc'", "/data/deployer/timeagent/vendor/cache/eye-51cdc5f92297/lib/eye/trigger/starting_guard.rb:28:in `block in check_start'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/call/sync.rb:16:in `dispatch'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/future.rb:18:in `block in new'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/celluloid-essentials-0.20.5/lib/celluloid/internals/thread_handle.rb:14:in `block in initialize'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/actor/system.rb:78:in `block in get_thread'", "/data/deployer/timeagent/vendor/bundle/ruby/2.3.0/gems/celluloid-0.17.3/lib/celluloid/group/spawner.rb:50:in `block in instantiate'"]
```

The other process is sending an identical request in a loop and has no delays at all, all the requests are working perfectly and quickly.

The exact same code, running from inside eye/celluloid, is intermittently timing out after 30 seconds of waiting :( - Any ideas what could be causing this?

Are there any known issues that freeze/affect HTTP requests when called from eye/celluloid? - any suggested alternatives?

**Comment by kostya** [comment]
no idea, maybe because trigger called with defer context (https://github.com/kostya/eye/blob/master/lib/eye/trigger/starting_guard.rb#L28) and this somehow crash Celluloid::IO. (just for fun you can try to remove defer from this line).
You can try standard `net/http`, which works in http check just fine. Also you can try something like `curl ...`

**Comment by xanview** [comment]
Thank you for the fast response, switching to net/http resolved this. It seems this is to do with timeout handling in http.rb - it's a shame as it is otherwise a great library :(

**Comment by kostya** [comment]
i think removing `defer` should fix this. But, i add defer for `system`, net/http and other thread blocking commands. So may be add option use defer or not.

**Comment by xanview** [comment]
Not sure if that would've helped, check this out: https://github.com/httprb/http/issues/401 -- the developer said that basically http.rb cannot make requests period if used with Celluloid::IO, yikes! - Great library when used outside of celluloid though.

**Comment by kostya** [comment]
seems you are using eye so long, how it is?

**Comment by xanview** [comment]
Absolutely fantastic!! - I've tried god and bluepill, even resorted to trying to write something myself and in desperation even tried to hack systemd (which really isn't suitable for something like this).

Nothing is nearly as usable as eye! Thank you for writing and maintaining it :)
