### ISSUE TITLE
Exception: attempted to call a dead actor: proc_cpu/proc_memory

### ISSUE THREAD

**Issue by maxwxzheng** [kostya/eye#221]
Hi! We are using eye to monitor our ruby sidekiq jobs. We are seeing the following error when brining up the jobs. Also the same issue with proc_memory. Not sure how to investigate this issue. Could anyone help? Thanks!

ERROR -- [leadgenie:sidekiq_processor:sidekiq_processor_9] Exception: attempted to call a dead actor: proc_cpu ["/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/proxy/sync.rb:9:in `method_missing'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/eye-0.10.0/lib/eye/system_resources.rb:26:in `start_time'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/eye-0.10.0/lib/eye/process/system.rb:44:in `compare_identity'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/eye-0.10.0/lib/eye/process/monitor.rb:14:in `load_external_pid_file'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/eye-0.10.0/lib/eye/process/controller.rb:7:in `start'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/eye-0.10.0/lib/eye/process/scheduler.rb:74:in `scheduler_consume'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/eye-0.10.0/lib/eye/process/scheduler.rb:126:in `scheduler_run'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `public_send'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/calls.rb:28:in `dispatch'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/call/async.rb:7:in `dispatch'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:50:in `block in dispatch'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/cell.rb:76:in `block in task'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/actor.rb:339:in `block in task'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/task.rb:44:in `block in initialize'", "/home/ubuntu/leadgenie/shared/bundle/ruby/2.5.0/gems/celluloid-0.17.3/lib/celluloid/task/fibered.rb:14:in `block in create'"]

**Comment by kostya** [comment]
this is quite strange, is it reprodusable? this should not happen. if you quit eye and start again?
